server:
  port: 80
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.huanxi.labsystem.dao.pojo
spring:
  datasource:
    url: jdbc:mysql://172.20.32.111:3306/labsystem
    username: labsystem
    password: huanxi
    driver-class-name: com.mysql.jdbc.Driver
